'\" t
.\"     Title: gst123
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/12/2023
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GST123" "1" "08/12/2023" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gst123 \- A GStreamer based command line media player
.SH "SYNOPSIS"
.sp
.nf
\fIgst123\fR [\fIOPTIONS\fR] [\fI<URIS>\&...\fR]
.fi
.SH "DESCRIPTION"
.sp
\fBgst123\fR is a command line based media player released as free software under the GNU LGPL\&.
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Shows a brief help message\&.
.RE
.PP
\-\-version
.RS 4
Prints out gst123 version\&.
.RE
.PP
\-\-full\-version
.RS 4
Prints out gst123 version and version of libraries used by gst123\&.
.RE
.PP
\-r, \-\-repeat
.RS 4
Repeat playlist forever\&.
.RE
.PP
\-z, \-\-shuffle
.RS 4
Shuffle playlist before playing\&.
.RE
.PP
\-Z, \-\-random
.RS 4
Play files in random order forever\&.
.RE
.PP
\-x, \-\-novideo
.RS 4
Do not play the video stream\&.
.RE
.PP
\-f, \-\-fullscreen
.RS 4
Use fullscreen video output\&.
.RE
.PP
\-@ <playlist>, \-\-list <playlist>
.RS 4
Load files to play from the playlist file\&.
.RE
.PP
\-a <driver>[=<device>], \-\-audio\-output <driver>[=<device>]
.RS 4
Set audio output driver (and device)\&. See section audio drivers for details\&.
.RE
.PP
\-v <plugin>, \-\-visualization <plugin>
.RS 4
Use a plugin for visualization during audio playback\&.
.RE
.PP
\-V, \-\-visualization\-list
.RS 4
Show a list of available audio visualization plugins which can be used with the \-v option\&.
.RE
.PP
\-k <n>, \-\-skip <n>
.RS 4
Skip the first
\fIn\fR
seconds of each file\&.
.RE
.PP
\-\-volume <volume>
.RS 4
Set initial replay volume (in percent)\&.
.RE
.PP
\-s <subtitle_file>, \-\-subtitle <subtitle_file>
.RS 4
Set subtitle file to use for video playback\&.
.RE
.PP
\-q, \-\-quiet
.RS 4
Don\(cqt display any messages (title, codec, ui feedback)\&.
.RE
.PP
\-\-verbose
.RS 4
Print GStreamer pipeline used to play files\&.
.RE
.sp
Besides filenames, playlist entries or command line args can be directories\&. In this case, \fBgst123\fR recursively searches the directory and plays all files contained in it\&.
.SH "INTERRUPT"
.sp
You can abort \fBgst123\fR at any time by pressing Ctrl\-C\&. If you are playing multiple files, this will stop the current file and begin playing the next one\&. If you want to abort playing immediately instead of skipping to the next file, press Ctrl\-C within the first second of the playback of a new file\&.
.SH "KEYBOARD INPUT"
.PP
cursor left/right
.RS 4
Seek 10 seconds backwards/forwards\&.
.RE
.PP
cursor down/up
.RS 4
Seek 1 minute backwards/forwards\&.
.RE
.PP
page down/up
.RS 4
Seek 10 minute backwards/forwards\&.
.RE
.PP
space
.RS 4
Toggle pause\&.
.RE
.PP
+/\-
.RS 4
Increase/decrease volume by 10%\&.
.RE
.PP
m
.RS 4
Toggle mute/unmute\&.
.RE
.PP
f
.RS 4
Toggle fullscreen display (only for videos)\&.
.RE
.PP
1
.RS 4
Normal video size (only for videos)\&.
.RE
.PP
A/a
.RS 4
Increase/decrease opacity by 10% (only for videos)\&.
.RE
.PP
s
.RS 4
Toggle subtitles (only for videos)\&.
.RE
.PP
r
.RS 4
Toggle playback direction, forward or reverse\&.
.RE
.PP
[ ]
.RS 4
Change playback rate to 10% faster/slower\&.
.RE
.PP
{ }
.RS 4
Change playback rate to 2x faster/slower\&.
.RE
.PP
Backspace
.RS 4
Change playback rate to normal speed, 1x\&.
.RE
.PP
n
.RS 4
Play next file\&.
.RE
.PP
q
.RS 4
Quit
\fBgst123\fR
.RE
.PP
?
.RS 4
Show keyboard help\&.
.RE
.SH "CONFIGURATION FILE"
.sp
During start, gst123 will read ~/\&.config/gst123rc, if this file exists\&. Empty lines and lines starting with a # are ignored\&. The following commands are available:
.PP
audio_output <driver>[=<device>]
.RS 4
This sets the default audio driver and the default audio device\&. It has the same effect as the \-a / \-\-audio\-output command line option\&. When both are present, a config file entry and the command line option, the value from the command line option will be used\&. Read the section on audio drivers for details on the available drivers and syntax\&.
.RE
.PP
visualization <visualization_plugin>
.RS 4
Set default visualization plugin for audio files\&. This setting has the same effect as the \-v / \-\-visualization command line option\&. When both are present, the value from the command line option will be used\&.
.RE
.SH "AUDIO DRIVERS"
.PP
alsa=<device>
.RS 4
The ALSA driver; when used without argument (as in \-a alsa), the ALSA driver uses the default device\&. To select an ALSA device, its possible to use for example alsa=hw:1 (which will use the hw:1 ALSA device)\&.
.RE
.PP
oss=<device>
.RS 4
The OSS driver; when used without argument (as in \-a oss), the OSS driver uses the default device\&. The device can be specified using for example oss=/dev/dsp1 (which would use the OSS device /dev/dsp1)\&.
.RE
.PP
pulse=<device>
.RS 4
The PulseAudio driver\&. This driver optionally accepts a device name using the pulse=<device> syntax\&.
.RE
.PP
jack
.RS 4
The JACK driver\&. Device selection is not supported in this case\&.
.RE
.PP
none
.RS 4
Dummy output driver, will not output any audio\&.
.RE
.SH "SEE ALSO"
.sp
gst123 Website (http://space\&.twc\&.de/~stefan/gst123\&.php)
