.\" generator: doxer.py 0.6
.\" generation: 2010-03-24T17:25:48
.TH "GST123" "1" "Wed Apr 19 00:50:37 2006" "beast-" "GST123 Manual Page"

.SH
NAME


.PP
gst123 - A GStreamer based command line media player
.SH
SYNOPSIS


.PP
\fBgst123\fP [\fIOPTIONS\fP] [\fIURIS...\fP]
.SH
DESCRIPTION


.PP
\fBgst123\fP is a command line based media player released as free
software under the GNU LGPL.
.SH
OPTIONS


.PP
\fBgst123\fP follows the usual GNU command line syntax, with long options starting with two dashes ('-').
.br

.br



.TP
\fB-h\fP, \fB--help\fP 
.br
Shows a brief help message.

.TP
\fB-v\fP, \fB--version\fP 
.br
Prints out \fBbeast\fP and component versions and file paths.

.TP
\fB-z\fP, \fB--shuffle\fP 
.br
Play files in pseudo random order.

.TP
\fB-@\fP \fI<playlist>\fP, \fB--list\fP \fI<playlist>\fP 
.br
Load files to play from the playlist file.

.TP
\fB--verbose\fP 
.br
Print GStreamer pipeline used to play files

.PP


.SH
SEE ALSO


.PP
BEAST/BSE Website (http://beast.gtk.org)
